name: "first github Action Demo"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print welcome message and OS
        run: |
          echo "Welcome to GitHub Actions using YAML"
          echo "Current OS is ${{ runner.os }}"
          echo "Github event name is ${{github.event_name}}"
          pwd
          ls ~
